services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-k
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minioadmin
      #miniok
      #miniokuser
    ports:
      - "0.0.0.0:9002:9002"
    volumes:
      - /home/mauro/minio/data:/data
    command: ["minio", "server", "/data", "--console-address", ":9002", "--address", ":9003"]
    networks:
      - api_bridge

volumes:
    miniodata:

networks:
  api_bridge:
    driver: bridge
